### ISSUE TITLE
Doesn't work against Preview2

### ISSUE THREAD

**Issue by nativ18** [florent37/Google-ARCore-Playground#1]
Crashes with log:
  Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                     at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                     at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                     at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                     at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                     at com.google.ar.core.Session.resume(Session.java:153)
                                                     at com.google.ar.core.examples.java.helloar.arcoremanager.ArCoreManager.lambda$setup$0$ArCoreManager(ArCoreManager.java:149)
                                                     at com.google.ar.core.examples.java.helloar.arcoremanager.ArCoreManager$$Lambda$0.accept(Unknown Source:0)
                                                     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)

**Comment by 18Gray** [comment]
遇到同样的问题

**Comment by cancanw** [comment]
遇到同样的问题

**Comment by cancanw** [comment]
这个好像只支持tango设备？
